var allSlogans = [
    "откройся cчастью",
    "open happiness",
    "be refreshed",
    "вливайся",
    "все будет",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Всегда",
    "Shake up for happiness",
    "Stay on the Coke side of life",
    "Coke goes with good times",
    "Праздник к нам приходит",
    "Delicious and refreshing",
    "It's the real thing",
    "Вливайся",
    "Have a Coke and a smile"
];

var allNames = [
    "Andreas",
    "Collin",
    "Jaime",
    "Александр",
    "Александр",
    "Алексей",
    "Алена",
    "Анастасия",
    "Богдана",
    "Борис",
    "Владимир",
    "Дарья",
    "Диана",
    "Дмитрий",
    "Евгений",
    "Евгения",
    "Елена",
    "Елена",
    "Инна",
    "Ирина",
    "Ирина",
    "Мария",
    "Ольга",
    "Ольга",
    "Светлана",
    "Татьяна",
    "Елена"
];