var allSlogans = [
    "откройся cчастью",
    "open happiness",
    "be refreshed",
    "вливайся",
    "все будет",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Coca-Cola&nbsp;+&nbsp;Gravity&nbsp;=",
    "Всегда",
    "Shake up for happiness",
    "Stay on the Coke side of life",
    "Coke goes with good times",
    "Праздник к нам приходит",
    "Delicious and refreshing",
    "It's the real thing",
    "Вливайся",
    "Have a Coke and a smile"
];

var allNames = [
    "Andreas Gregoriou",
    "Collin Brum",
    "Jaime Pysola",
    "Александр Прокофьев",
    "Александр Овечкин",
    "Алексей Савилов",
    "Алена Бузлукова",
    "Анастасия Синягина",
    "Богдана Яворская",
    "Борис Корягин",
    "Владимир Кравцов",
    "Дарья Шик",
    "Диана Мальцева",
    "Дмитрий Музыченко",
    "Евгений Евсиков",
    "Евгения Мур",
    "Елена Рогалева",
    "Елена Трунова",
    "Инна Ким",
    "Ирина Батюнина",
    "Ирина Герман",
    "Мария Логвиненко",
    "Ольга Молчанова",
    "Ольга Новик",
    "Светлана Сутугина",
    "Татьяна Григорьева",
    "Елена Ивченко"
];